# Site settings
title: 'Arul&#039;s Blog'
email: arulk@live.com
description: > # this means to ignore newlines until "baseurl:"
  Site about everything and nothing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arulweb.com" # the base hostname & protocol for your site
twitter_username: arulkumaravel
github_username:  arulk

# Build settings
markdown: kramdown
highlighter: 'pygments'
